apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16.1-alpine3.18
        env:
        - name: POSTGRES_DB
          value: crow
        - name: POSTGRES_USER
          value: crow
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crow-secrets
              key: DATABASE_PASSWORD
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        - name: config-volume
          mountPath: /etc/postgresql
          readOnly: true

      volumes:
      - name: config-volume
        configMap:
          name: pg-hba-config
  volumeClaimTemplates:
  - metadata:
      name: postgresql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 64Gi
