apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/doktorupnos/crow/backend:master
          ports:
            - containerPort: 8000
          env:
            - name: ADDR
              value: ":8000"
            - name: CORS_ORIGIN
              value: "http://*"
            - name: JWT_SECRET
              value: "+3xObWCCIAQf/N1ltJD27kZ5gfjmfbUBG4ViZ/6oHI3rpVFmhAo7yzwWg4mivB1Jea8UuwooegxTdZhZgLkZZA=="
            - name: JWT_LIFETIME
              value: "1h"
            - name: DSN
              value: "postgres://postgres:kolaratoustefanou@postgres:5432/crow"
            - name: DEFAULT_POSTS_PAGE_SIZE
              value: "5"
            - name: DEFAULT_FOLLOWS_PAGE_SIZE
              value: "10"
