version: 2
updates:
  - package-ecosystem: "npm"
    directory: "web"
    schedule:
      interval: "daily"
  - package-ecosystem: "golang"
    directory: "backend"
    schedule:
      interval: "daily"
