version: 2
updates:

  # Maintain dependencies for NodeJS
  - package-ecosystem: "npm"
    directory: "web"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "backend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
