version: '3'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crow
    volumes:
      - ./persistence/postgres-config:/etc/postgresql
    networks:
      - crownet
    ports:
      - "5432:5432"

  backend:
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - crownet
    environment:
      - ADDR="localhost:8000"
      - CORS_ORIGIN="http://*"
      - DSN="postgres://postgres:postgres@localhost:5432/crow"
      - JWT_SECRET="+3xObWCCIAQf/N1ltJD27kZ5gfjmfbUBG4ViZ/6oHI3rpVFmhAo7yzwWg4mivB1Jea8UuwooegxTdZhZgLkZZA=="
      - JWT_LIFETIME="1h"
      - DEFAULT_POSTS_PAGE_SIZE="5"
      - DEFAULT_FOLLOWS_PAGE_SIZE="10"

    build: "./backend"
    depends_on:
      - postgres
  web:
     restart: on-failure
     ports:
       - "3000:3000"
     networks:
       - crownet
     build: "./web"
     depends_on:
       - postgres
       - backend

networks:
  crownet:
