// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFollow(ctx context.Context, arg CreateFollowParams) error
	CreateLike(ctx context.Context, arg CreateLikeParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	FollowsUser(ctx context.Context, arg FollowsUserParams) (bool, error)
	GetFollowerCount(ctx context.Context, followee uuid.UUID) (int64, error)
	GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error)
	GetFollowing(ctx context.Context, arg GetFollowingParams) ([]GetFollowingRow, error)
	GetFollowingCount(ctx context.Context, follower uuid.UUID) (int64, error)
	GetLikesForPost(ctx context.Context, postID uuid.UUID) (int64, error)
	GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error)
	GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]GetPostsByUserRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	UserLikesPost(ctx context.Context, arg UserLikesPostParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
