apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/doktorupnos/crow/web:master
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
