version: "2"
linters:
  enable:
    - gosec
    - containedctx
    - contextcheck
    # - dupl
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - iface
    - interfacebloat
    - ireturn
    - musttag
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    # - wrapcheck
