name: Test API

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'api/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'api/**'

env:
  REGISTRY: ghcr.io/doktorupnos
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-testing:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          ecr: auto
          logout: true

      - name: Build API image
        run: |

            docker build api -t ${{ env.REGISTRY }}/wip-chat/api:${GITHUB_REF##*/}

      - name: Push API image
        run: |
            docker push ${{ env.REGISTRY }}/wip-chat/api:${GITHUB_REF##*/}

