name: API CI

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            api/
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: 🧪 Tests
        run: go test -v ./...
        working-directory: ./api

      - name: Formatting
        run: test -z $(go fmt ./...)

      - name: vet
        run: go vet ./...

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest
          working-directory: ./api

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
