name: Release API to Production

on:
  workflow_dispatch:
    tags:
      - '*'
jobs:
  build-testing:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v2.2.0
        with:
          registry: doktorupnos/wip-chat
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: auto
          logout: true

      - name: Build API image
        run: |
            docker build api -t doktorupnos/wip-chat/api:${GITHUB_REF##*/}

      - name: Push API image
        run: |
            docker push doktorupnos/wip-chat/api:${GITHUB_REF##*/}

