name: Test WebApp

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'web/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'web/**'

env:
  REGISTRY: ghcr.io/doktorupnos
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-testing:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          ecr: auto
          logout: true

      - name: Build WebApp image
        run: |
            docker build web -t ${{ env.REGISTRY }}/${{ github.event.repository.name }}/web:${GITHUB_REF##*/}

      - name: Push WebApp image
        run: |
            docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}/web:${GITHUB_REF##*/}

